[package]
name = "blobs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
macroquad = "0.4.13"
rapier2d = "0.22.0"

[[bin]]
name = "rapier_init"

[[bin]]
name = "rapier_blob"

[[bin]]
name = "blob"

